services:
    doctrine.dbal.connection_factory:
        class: Sidus\EncryptionBundle\Doctrine\Connection\Factory\ConnectionFactory
        autowire: true
        autoconfigure: true
        arguments:
            $typesConfig: "%doctrine.dbal.connection_factory.types%"
            $valueEncrypter: '@Sidus\EncryptionBundle\Doctrine\ValueEncrypterInterface'
