services:
    Sidus\EncryptionBundle\Encryption\XChaChaPolySodiumEncryptionAdapter:
        class: Sidus\EncryptionBundle\Encryption\XChaChaPolySodiumEncryptionAdapter
        public: false
        tags:
            - { name: sidus.encryption.adapter }

    Sidus\EncryptionBundle\Encryption\Aes256GcmSodiumEncryptionAdapter:
        class: Sidus\EncryptionBundle\Encryption\Aes256GcmSodiumEncryptionAdapter
        public: false
        tags:
            - { name: sidus.encryption.adapter }
    
    Sidus\EncryptionBundle\Encryption\Rijndael256MCryptEncryptionAdapter:
        class: Sidus\EncryptionBundle\Encryption\Rijndael256MCryptEncryptionAdapter
        public: false
        tags:
            - { name: sidus.encryption.adapter }

    Sidus\EncryptionBundle\Encryption\Enabler\EncryptionEnablerInterface: '@Sidus\EncryptionBundle\Encryption\Enabler\EncryptionEnabler'
    
    Sidus\EncryptionBundle\Encryption\Enabler\EncryptionEnabler:
        class: Sidus\EncryptionBundle\Encryption\Enabler\EncryptionEnabler
        public: false

    Sidus\EncryptionBundle\Doctrine\ValueEncrypter:
        class: Sidus\EncryptionBundle\Doctrine\ValueEncrypter
        public: false
        arguments:
            - '@Sidus\EncryptionBundle\Registry\EncryptionManagerRegistryInterface'
            - '@logger'
            - '@Sidus\EncryptionBundle\Encryption\Enabler\EncryptionEnablerInterface'
            
    Sidus\EncryptionBundle\Doctrine\ValueEncrypterInterface: '@Sidus\EncryptionBundle\Doctrine\ValueEncrypter'
