parameters:
    security.authentication.provider.dao.class: Sidus\EncryptionBundle\Authentication\AuthenticationProvider

services:
    ##
    # Inherit the original Dao Provider from symfony and add the encryption manager
    # @see symfony/src/Symfony/Bundle/SecurityBundle/Resources/config/security_listeners.xml
    ##
    security.authentication.provider.dao:
        class: Sidus\EncryptionBundle\Authentication\AuthenticationProvider
        arguments:
            - ~
            - '@security.user_checker'
            - ~
            - '@security.encoder_factory'
            - '%security.authentication.hide_user_not_found%'
        calls:
             - [setEncryptionManager, ['@sidus.encryption.manager']]

    sidus.encryption.manager.adapter:
        class: Sidus\EncryptionBundle\Encryption\XChaChaPolySodiumEncryptionAdapter

    sidus.encryption.manager:
        class: Sidus\EncryptionBundle\Encryption\EncryptionManager
        arguments:
            - '@sidus.encryption.manager.adapter'
            - '@session'
            - '@?debug.stopwatch'

    sidus.encryption.subscriber:
        class: Sidus\EncryptionBundle\EventSubscriber\CryptableSubscriber
        arguments:
            - '@sidus.encryption.manager'
            - '@?logger'
        tags:
            - { name: doctrine.event_subscriber, connection: default }
