services:
    Sidus\EncryptionBundle\Registry\EncryptionManagerRegistry:
        class: Sidus\EncryptionBundle\Registry\EncryptionManagerRegistry
        public: false
        arguments:
            - ~
